# Player settings.

MAGE_CONSTANTS = {
    "PLAYER_WALK_SPEED": 5,
    "PLAYER_RUN_SPEED": 15,
    "PLAYER_SNEAK_SPEED": 2,
    "FAIRE_FIRE_COOLDOWN": 800,
    "FAIRE_FIRE_VELOCITY": 10,
    "FAIRE_FIRE_BASE_DAMAGE": 10,
    "CONCENTRATION_DAMAGE_MODIFIER": 1.5,
    "CONCENTRATION_COOLDOWN": 1600,
    "TELEPORT_VELOCITY": 50,
    "TELEPORT_COOLDOWN": 1600
}
